// // Mocks generated by Mockito 5.4.6 from annotations
// // in hi_net/test/unit_testing/auth_test/auth_test.dart.
// // Do not manually edit this file.

// // ignore_for_file: no_leading_underscores_for_library_prefixes
// import 'dart:async' as _i5;

// import 'package:dartz/dartz.dart' as _i3;
// import 'package:hi_net/data/network/api.dart' as _i4;
// import 'package:hi_net/data/network/error_handler/failure.dart' as _i8;
// import 'package:hi_net/data/request/request.dart' as _i6;
// import 'package:hi_net/data/responses/responses.dart' as _i2;
// import 'package:hi_net/domain/usecase/login_usecase.dart' as _i7;
// import 'package:mockito/mockito.dart' as _i1;

// // ignore_for_file: type=lint
// // ignore_for_file: avoid_redundant_argument_values
// // ignore_for_file: avoid_setters_without_getters
// // ignore_for_file: comment_references
// // ignore_for_file: deprecated_member_use
// // ignore_for_file: deprecated_member_use_from_same_package
// // ignore_for_file: implementation_imports
// // ignore_for_file: invalid_use_of_visible_for_testing_member
// // ignore_for_file: must_be_immutable
// // ignore_for_file: prefer_const_constructors
// // ignore_for_file: unnecessary_parenthesis
// // ignore_for_file: camel_case_types
// // ignore_for_file: subtype_of_sealed_class
// // ignore_for_file: invalid_use_of_internal_member

// class _FakeRegisterResponse_0 extends _i1.SmartFake
//     implements _i2.RegisterResponse {
//   _FakeRegisterResponse_0(Object parent, Invocation parentInvocation)
//     : super(parent, parentInvocation);
// }

// class _FakeUserResponse_1 extends _i1.SmartFake implements _i2.UserResponse {
//   _FakeUserResponse_1(Object parent, Invocation parentInvocation)
//     : super(parent, parentInvocation);
// }

// class _FakeBasicResponse_2 extends _i1.SmartFake implements _i2.BasicResponse {
//   _FakeBasicResponse_2(Object parent, Invocation parentInvocation)
//     : super(parent, parentInvocation);
// }

// class _FakeEither_3<L, R> extends _i1.SmartFake implements _i3.Either<L, R> {
//   _FakeEither_3(Object parent, Invocation parentInvocation)
//     : super(parent, parentInvocation);
// }

// /// A class which mocks [AppServices].
// ///
// /// See the documentation for Mockito's code generation for more information.
// class MockAppServices extends _i1.Mock implements _i4.AppServices {
//   @override
//   _i5.Future<_i2.RegisterResponse> register(
//     _i6.RegisterRequest? registerRequest,
//   ) =>
//       (super.noSuchMethod(
//             Invocation.method(#register, [registerRequest]),
//             returnValue: _i5.Future<_i2.RegisterResponse>.value(
//               _FakeRegisterResponse_0(
//                 this,
//                 Invocation.method(#register, [registerRequest]),
//               ),
//             ),
//             returnValueForMissingStub: _i5.Future<_i2.RegisterResponse>.value(
//               _FakeRegisterResponse_0(
//                 this,
//                 Invocation.method(#register, [registerRequest]),
//               ),
//             ),
//           )
//           as _i5.Future<_i2.RegisterResponse>);

//   @override
//   _i5.Future<_i2.UserResponse> verifyOtp(
//     _i6.VerifyOtpRequest? verifyOtpRequest,
//   ) =>
//       (super.noSuchMethod(
//             Invocation.method(#verifyOtp, [verifyOtpRequest]),
//             returnValue: _i5.Future<_i2.UserResponse>.value(
//               _FakeUserResponse_1(
//                 this,
//                 Invocation.method(#verifyOtp, [verifyOtpRequest]),
//               ),
//             ),
//             returnValueForMissingStub: _i5.Future<_i2.UserResponse>.value(
//               _FakeUserResponse_1(
//                 this,
//                 Invocation.method(#verifyOtp, [verifyOtpRequest]),
//               ),
//             ),
//           )
//           as _i5.Future<_i2.UserResponse>);

//   @override
//   _i5.Future<_i2.BasicResponse> logout(_i6.LogoutRequest? logoutRequest) =>
//       (super.noSuchMethod(
//             Invocation.method(#logout, [logoutRequest]),
//             returnValue: _i5.Future<_i2.BasicResponse>.value(
//               _FakeBasicResponse_2(
//                 this,
//                 Invocation.method(#logout, [logoutRequest]),
//               ),
//             ),
//             returnValueForMissingStub: _i5.Future<_i2.BasicResponse>.value(
//               _FakeBasicResponse_2(
//                 this,
//                 Invocation.method(#logout, [logoutRequest]),
//               ),
//             ),
//           )
//           as _i5.Future<_i2.BasicResponse>);

//   @override
//   _i5.Future<_i2.UserResponse> login(_i6.LoginRequest? loginRequest) =>
//       (super.noSuchMethod(
//             Invocation.method(#login, [loginRequest]),
//             returnValue: _i5.Future<_i2.UserResponse>.value(
//               _FakeUserResponse_1(
//                 this,
//                 Invocation.method(#login, [loginRequest]),
//               ),
//             ),
//             returnValueForMissingStub: _i5.Future<_i2.UserResponse>.value(
//               _FakeUserResponse_1(
//                 this,
//                 Invocation.method(#login, [loginRequest]),
//               ),
//             ),
//           )
//           as _i5.Future<_i2.UserResponse>);
// }

// /// A class which mocks [LoginUseCase].
// ///
// /// See the documentation for Mockito's code generation for more information.
// class MockLoginUseCase extends _i1.Mock implements _i7.LoginUseCase {
//   @override
//   _i5.Future<_i3.Either<_i8.Failure, _i2.UserResponse>> execute(
//     _i6.LoginRequest? input,
//   ) =>
//       (super.noSuchMethod(
//             Invocation.method(#execute, [input]),
//             returnValue:
//                 _i5.Future<_i3.Either<_i8.Failure, _i2.UserResponse>>.value(
//                   _FakeEither_3<_i8.Failure, _i2.UserResponse>(
//                     this,
//                     Invocation.method(#execute, [input]),
//                   ),
//                 ),
//             returnValueForMissingStub:
//                 _i5.Future<_i3.Either<_i8.Failure, _i2.UserResponse>>.value(
//                   _FakeEither_3<_i8.Failure, _i2.UserResponse>(
//                     this,
//                     Invocation.method(#execute, [input]),
//                   ),
//                 ),
//           )
//           as _i5.Future<_i3.Either<_i8.Failure, _i2.UserResponse>>);
// }
